### PR TITLE
Ported Chat Demo to C#

### PR DESCRIPTION
**Pull request by ElanHasson**
Ported the F# Chat Client/Server demo to C#.

### CODE REVIEW

**Comment by yevhen** [comment]
1) No need to create CSharp solution folder since C# is default development language. Same applies to folder/project paths. Please remove CSharp so that naming is consistent with rest of C# examples. 

2) Also, creating top-level Demos solution folder is unnecessary. I'd like to have a single demo which shows (almost) every feature in action, including TestKit. Chat server only showcases client/cluster setup and observers - I think it's better to move it to examples. We'll probably do the same with F# demos - will just leave one of them (the most comprehensive one) and will move the rest to examples.

3) We're using 5.6.3 version of Azure storage package. You've referenced 5.6.4 and that creating an issues with CI build since assemblies got overwritten with newer version. Either you need to migrate (update) the rest of package/assembly references to 5.6.4 or just be consistent with the rest of the solution and use 5.6.3. I prefer the latter - since it will greatly reduce the number of changes irrelevant to the essence of your PR :smile: 

4) Please revert formatting changes in the following files:
     - Source/Orleankka/Utility/AssemblyExtensions.cs
     - Source/FSharp.Demo.HelloWorld/Program.fs
     - Source/FSharp.Demo.Chat.Server/ChatServer.fs

Note: we're using spaces for formatting (4 spaces per tab).

5) I'll check the actual Chat code tomorrow :)

Thanks!

**Comment by ElanHasson** [comment]
I have to dig into the errors and see why the tests are failing.

Anyone spot anything they recognize?

**Comment by ElanHasson** [comment]
1) Moved to Examples and renamed the projects to Example.Chat.Client/Server to match the folder names.
2) Moved to Examples
3) Sorry about that. This is what Azure Storage brought it when I added the Orleankka package. I've corrected it to match.
4) Reverted formatting changes in files listed above.

**Comment by yevhen** [comment]
Build is failing due to orphan packages.config references in Repositories.config (https://ci.appveyor.com/project/yevhen/orleankka/build/122). That's because you've removed old chat demos. Simple to fix - just remove those from Repositories.config:)

**Comment by yevhen** [comment]
Now to the meat :smile: 

As I said before, I'd like C# chat server example to showcase something unique, something not already covered by other examples. I think I figured out what it will be.

That should be *Streams* !!! F# chat demo uses observers while C# will be using streams. It will be a great example of utilizing streams. The page on Orleans streams [here](http://dotnet.github.io/orleans/Orleans-Streams/) describes exactly this use-case for chat rooms. Basically, we will treat chat room as just a stream, with stream id equal to chat room name.

That should be really cool example and you will learn something new again :)

**Comment by yevhen** [comment]
Continuation ...

If we transfer stream-based chat room example from Orelans' Streams page to your example:
- No need to do registration of users (clients) in ChatServer and use observers
- No need for ChatServer as actor at all
- In client app you wil simply ask for a user name and what chat room to join
- Then you will subscribe to stream with the chat room name entered by the user
- That's it

**Comment by gabikliot** [comment]
This is awesome @Yevhen! So stream is an actor, or actor is a stream? 😃 neither? Both? Cc @sergeybykov

**Comment by ElanHasson** [comment]
@yevhen I will reimplement, but I think it would be best as a separate sample.

**Comment by yevhen** [comment]
Well, leave it as is. I'll do another myself. It will be a 3rd chat demo :)

**Comment by yevhen** [comment]
@gabikliot 
> This is awesome @Yevhen! So stream is an actor, or actor is a stream? :smiley: neither? Both? Cc @sergeybykov

Not sure if that was an irony on your part or not (Internet is such a bad medium), but here an explanation for you :)

In Elan's example, [ChatServer](https://github.com/ElanHasson/Orleankka/blob/master/Source/Example.Chat.TypedActor.Server/ChatServer.cs) have the following responsibilities:

1. Maintain a list of connected users which are just a list of observer references bound to a particular user name - that's basically covered by Stream's PubSub capability
2. Notify all connected users (via observer references) when one of them post a message to chat - covered by Stream's broadcast capability

No any other logic is there. Basically, we can drop the ChatServer altogether and just use Stream for that. That's an idea described in your Stream documentation page. It's something I agree with since we can view a chat room as just a projection of all events that happened to it. Without any additional business-logic, constraints/invariants - it's just a stupid projection :)

As usual I want to kill 2 birds with the one stone: integrate Elan's work and also showcase something that was not covered by other samples elsewhere :)

@gabikliot  Make sense?

**Comment by gabikliot** [comment]
@yevhen , that was indeed a joke on my part.
The suggestion to use streams, just like you outlined, makes a total sense to me. And killing 2 birds with the one stone even more sense.

The "joke" was: with this using of streams you can, in theory, say that now the chat stream behaves like an actor. No real Actor behind it, but mentally, logically, stream behaves as an actor. I am not sure how this way on thinking about the duality of actors and streams is useful. What I really care is that you can use streams to solve it, it works, and makes your code better (smaller, more robust). The "theoretical duality" is just a mental exercise.

**Comment by yevhen** [comment]
I was always thinking about streams as being backed by actors ;)

**Comment by gabikliot** [comment]
Logically, right? There is no physical actors behind Orleans streams. 
I think Akka streams have a different approach on that. There the stream is an actor (physically). In Orleans a stream is a way for actors to communicate. It is the blue line between red elements in my presentation. It is an edge in the graph, not a vertex.

**Pull request merged**
